name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  lint:
    name: Rust clippy on nightly
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - run: cargo clippy

  test:
    name: Project ${{matrix.project}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [ builder, debug, seq, sorted, bitfield ]
    env:
      GIT_COMMITTER_EMAIL: proc-macro-workshop@dtolnay.github.io
      GIT_COMMITTER_NAME: proc-macro-workshop CI
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test
        working-directory: ${{matrix.project}}
